<?php
$this->title = "My Users";
$this->headTitle($this->title);
?>
<p><a href="<?php echo $this->url(array('controller'=>'user',
'action'=>'add'));?>">Add new user</a></p>
<table>
    <tr>
    <th>Name</th>
    <th>Email</th>
    <th>&nbsp;</th>
    </tr>
    <?php foreach($this->users as $user) : ?>
    <tr>
        <td><?php echo $this->escape($user->name);?></td>
        <td><?php echo $this->escape($user->email);?></td>
        <td>
            <a href="<?php echo $this->url(array('controller'=>'user',
            'action'=>'edit', 'iduser'=>$user->iduser));?>">Edit</a>
            <a href="<?php echo $this->url(array('controller'=>'user',
            'action'=>'delete', 'iduser'=>$user->iduser));?>">Delete</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
